name: restaurant
description: A smart restaurant management system

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  google_fonts: ^6.1.0 
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/food1.jpg
    - assets/food2.jpg
    - assets/food3.jpg